name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
            REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
            REACT_APP_AUTH_CLIENT_ID: ${{secrets.REACT_APP_AUTH_CLIENT_ID}}
            REACT_APP_AUTH_AUDIENCE: ${{secrets.REACT_APP_AUTH_AUDIENCE}}
        steps:
            - uses: actions/checkout@v2

            - name: Create ssh-key file
              run: |
                mkdir ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -t rsa github.com

            - name: Use NodeJS v.15
              uses: actions/setup-node@v1
              with:
                  node-version: '15.x'

            - name: NPM install
              run: npm ci

            - name: NPM build
              run: CI='' npm run build

            - name: List files
              run: cd ./build && ls -la

            - name: Copy to server
              run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" build/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/www/static/
